module.exports = function($translateProvider){
  $translateProvider.translations('ca', {
    'BACK': 'Enrere',
    'DELETE': 'Suprimeix',
    'CREATE': 'Crea',
    'EDIT': 'Modifica',
    'EXPORT': 'Exporta',
    'ADD_FILTER': 'Filtra',
    'SEE_RELATED': 'Veure els {{ entityName }} relacionats',
    'LIST': 'Llista',
    'SHOW': 'Detalls',
    'SAVE': 'Guardar',
    'N_SELECTED': '{{ length }} seleccionats',
    'ARE_YOU_SURE': 'Aquesta modificació no es pot desfer. N\'estàs segur?',
    'YES': 'Confirma',
    'NO': 'Cancel·la',
    'FILTER_VALUES': 'Escriu o selecciona un element',
    'CLOSE': 'Tanca',
    'CLEAR': 'Buida',
    'CURRENT': 'Actual',
    'REMOVE': 'Esborra',
    // 'ADD_NEW': 'Afegir {{ name }}',
    'ADD_NEW': 'Nou element',
    'BROWSE': 'Busca',
    'N_COMPLETE': '{{ progress }}% completat',
    'CREATE_NEW': 'Crea',
    'SUBMIT': 'Envia',
    'SAVE_CHANGES': 'Guarda els canvis',
    'BATCH_DELETE_SUCCESS': 'Esborrat completat',
    'DELETE_SUCCESS': 'Esborrat completat',
    'ERROR_MESSAGE': 'Error en el servidor (codi: {{ status }})',
    'INVALID_FORM': 'Formulari invàlid',
    'CREATION_SUCCESS': 'Registre completat',
    'EDITION_SUCCESS': 'Modificació completada',
    'ACTIONS': 'Accions',
    'PAGINATION': '<strong>{{ begin }}</strong> - <strong>{{ end }}</strong> de <strong>{{ total }}</strong>',
    'NO_PAGINATION': 'No hi ha resultats',
    'PREVIOUS': '« Anterior',
    'NEXT': 'Següent »',
    'DETAIL': 'Detall',
    'STATE_CHANGE_ERROR': 'Error de ruta: {{ message }}',
    'NOT_FOUND': 'Pàgina no trobada',
    'NOT_FOUND_DETAILS': 'La pàgina sol·licitada no existeix. Torna a la pàgina anterior i prova-ho de nou.',

    // CUSTOM
  });
  $translateProvider.translations('es', {
    'BACK': 'Atrás',
    'DELETE': 'Suprimir',
    'CREATE': 'Crear',
    'EDIT': 'Modificar',
    'EXPORT': 'Exportar',
    'ADD_FILTER': 'Filtrar',
    'SEE_RELATED': 'Ver l@s {{ entityName }} relacionados',
    'LIST': 'Lista',
    'SHOW': 'Detalles',
    'SAVE': 'Guardar',
    'N_SELECTED': '{{ length }} seleccionados',
    'ARE_YOU_SURE': 'Esta modificación no se puede deshacer. ¿Estás seguro?',
    'YES': 'Confirmar',
    'NO': 'Cancelar',
    'FILTER_VALUES': 'Escribe o selecciona un elemento',
    'CLOSE': 'Cerrar',
    'CLEAR': 'Vaciar',
    'CURRENT': 'Actual',
    'REMOVE': 'Borrar',
    // 'ADD_NEW': 'Añadir {{ name }}',
    'ADD_NEW': 'Añadir elemento',
    'BROWSE': 'Buscar',
    'N_COMPLETE': '{{ progress }}% completado',
    'CREATE_NEW': 'Crear',
    'SUBMIT': 'Enviar',
    'SAVE_CHANGES': 'Guardar cambios',
    'BATCH_DELETE_SUCCESS': 'Borrado completado',
    'DELETE_SUCCESS': 'Borrado completado',
    'ERROR_MESSAGE': 'Error en el servidor (código: {{ status }})',
    'INVALID_FORM': 'Formulario inválido',
    'CREATION_SUCCESS': 'Registro completado',
    'EDITION_SUCCESS': 'Modificación completada',
    'ACTIONS': 'Acciones',
    'PAGINATION': '<strong>{{ begin }}</strong> - <strong>{{ end }}</strong> de <strong>{{ total }}</strong>',
    'NO_PAGINATION': 'No hay resultados',
    'PREVIOUS': '« Anterior',
    'NEXT': 'Siguiente »',
    'DETAIL': 'Detalle',
    'STATE_CHANGE_ERROR': 'Error de ruta: {{ message }}',
    'NOT_FOUND': 'Página no encontrada',
    'NOT_FOUND_DETAILS': 'La página solicitada no existe. Vuelve a la página anterior e inténtalo de nuevo.',

    // CUSTOM
  });
  $translateProvider.preferredLanguage('es');
};
